import 'package:fluentui_system_icons/fluentui_system_icons.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:gap/gap.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:utakula_v2/common/helpers/helper_utils.dart';
import 'package:utakula_v2/common/themes/theme_utils.dart';
import 'package:utakula_v2/features/foods/domain/entities/calorie_entity.dart';
import 'package:utakula_v2/features/foods/domain/entities/food_entity.dart';
import 'package:utakula_v2/features/foods/domain/entities/meal_plan_enum.dart';
import 'package:utakula_v2/features/foods/presentation/providers/foods_provider.dart';
import 'package:utakula_v2/features/foods/data/models/calorie_model.dart';

class AddFoods extends HookConsumerWidget {
  const AddFoods({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final formKey = useMemoized(() => GlobalKey<FormState>());
    final foodNameController = useTextEditingController();
    final imageUrlController = useTextEditingController();
    final selectedMacroNutrient = useState<String?>(null);
    final selectedMealType = useState<MealTypeEnum?>(null);
    HelperUtils helperUtils = HelperUtils();

    // Calorie breakdown controllers
    final totalCaloriesController = useTextEditingController();
    final carbsController = useTextEditingController();
    final proteinsController = useTextEditingController();
    final fatsController = useTextEditingController();
    final fiberController = useTextEditingController();
    final sugarController = useTextEditingController();

    final isSubmitting = useState(false);
    final currentStep = useState(0); // 0: Food Details, 1: Calorie Data

    final macroNutrients = ['Carbohydrate', 'Protein', 'Fat', 'Mixed'];

    void handleSubmit() async {
      if (formKey.currentState?.validate() ?? false) {
        isSubmitting.value = true;

        try {
          // Parse amounts
          final carbsAmount = double.tryParse(carbsController.text) ?? 0;
          final proteinsAmount = double.tryParse(proteinsController.text) ?? 0;
          final fatsAmount = double.tryParse(fatsController.text) ?? 0;
          final fiberAmount = double.tryParse(fiberController.text) ?? 0;

          // Calculate calories (carbs: 4cal/g, protein: 4cal/g, fat: 9cal/g, fiber: 2cal/g)
          final carbsCalories = carbsAmount * 4;
          final proteinsCalories = proteinsAmount * 4;
          final fatsCalories = fatsAmount * 9;
          final fiberCalories = fiberAmount * 2;

          final totalCalculated =
              carbsCalories + proteinsCalories + fatsCalories + fiberCalories;

          // Create NutrientBreakdown objects
          final carbohydrateBreakdown = NutrientBreakdown(
            amount: carbsAmount,
            calories: carbsCalories,
            unit: 'g',
          );

          final proteinBreakdown = NutrientBreakdown(
            amount: proteinsAmount,
            calories: proteinsCalories,
            unit: 'g',
          );

          final fatBreakdown = NutrientBreakdown(
            amount: fatsAmount,
            calories: fatsCalories,
            unit: 'g',
          );

          final fiberBreakdown = NutrientBreakdown(
            amount: fiberAmount,
            calories: fiberCalories,
            unit: 'g',
          );

          // Create the FoodEntity with proper CalorieEntity structure
          final foodEntity = FoodEntity(
            id: '',
            // Will be generated by backend
            name: foodNameController.text,
            imageUrl: imageUrlController.text,
            macroNutrient: selectedMacroNutrient.value!,
            mealType: selectedMealType.value!,
            calories: CalorieEntity(
              id: '',
              // Will be generated by backend
              foodId: '',
              // Will be set by backend
              total: totalCalculated.round(),
              carbohydrate: carbohydrateBreakdown,
              protein: proteinBreakdown,
              fat: fatBreakdown,
              fiber: fiberBreakdown,
            ),
          );

          // Call the repository method
          final result = await ref
              .read(foodsRepositoryProvider)
              .createFood(foodEntity);

          if (result.isRight()) {
            isSubmitting.value = false;

            if (context.mounted) {
              helperUtils.showSnackBar(
                context,
                "Food Added Successfully",
                ThemeUtils.$success,
              );
            }
          } else {
            isSubmitting.value = false;
          }
        } catch (e) {
          isSubmitting.value = false;
          if (context.mounted) {
            helperUtils.showSnackBar(
              context,
              'Error: ${e.toString()}',
              ThemeUtils.$error,
            );
          }
        }
      }
    }

    return Scaffold(
      backgroundColor: ThemeUtils.$backgroundColor,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(FluentIcons.arrow_left_24_filled),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Add New Food',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: Form(
          key: formKey,
          child: Column(
            children: [
              // Progress Indicator
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 16,
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: _buildStepIndicator(
                        step: 1,
                        title: 'Food Details',
                        isActive: currentStep.value == 0,
                        isCompleted: currentStep.value > 0,
                      ),
                    ),
                    Container(
                      width: 40,
                      height: 2,
                      color: currentStep.value > 0
                          ? ThemeUtils.$primaryColor
                          : Colors.grey[300],
                    ),
                    Expanded(
                      child: _buildStepIndicator(
                        step: 2,
                        title: 'Nutrition',
                        isActive: currentStep.value == 1,
                        isCompleted: false,
                      ),
                    ),
                  ],
                ),
              ),

              Expanded(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  child: Column(
                    children: [
                      if (currentStep.value == 0) ...[
                        // Step 1: Food Details
                        _buildSectionCard(
                          icon: FluentIcons.food_24_filled,
                          title: 'Food Information',
                          children: [
                            _buildTextField(
                              controller: foodNameController,
                              label: 'Food Name',
                              hint: 'e.g., Brown Rice',
                              icon: FluentIcons.text_32_regular,
                              validator: (value) {
                                if (value?.isEmpty ?? true) {
                                  return 'Please enter food name';
                                }
                                return null;
                              },
                            ),
                            const Gap(16),
                            _buildTextField(
                              controller: imageUrlController,
                              label: 'Image URL',
                              hint: 'image.jpg',
                              icon: FluentIcons.image_24_regular,
                              validator: (value) {
                                if (value?.isEmpty ?? true) {
                                  return 'Please enter image URL';
                                }
                                return null;
                              },
                            ),
                            const Gap(16),
                            _buildStringDropdown(
                              label: 'Macro Nutrient',
                              hint: 'Select primary nutrient',
                              icon: FluentIcons.molecule_24_regular,
                              value: selectedMacroNutrient.value,
                              items: macroNutrients,
                              onChanged: (value) {
                                selectedMacroNutrient.value = value;
                              },
                            ),
                            const Gap(16),
                            _buildMealTypeDropdown(
                              label: 'Meal Type',
                              hint: 'Select meal type',
                              icon: FluentIcons.clock_24_regular,
                              value: selectedMealType.value,
                              items: MealTypeEnum.values,
                              onChanged: (value) {
                                selectedMealType.value = value;
                              },
                            ),
                          ],
                        ),
                      ] else ...[
                        // Step 2: Calorie Data
                        _buildSectionCard(
                          icon: FluentIcons.data_pie_24_filled,
                          title: 'Macronutrient Breakdown',
                          children: [
                            Row(
                              children: [
                                Expanded(
                                  child: _buildTextField(
                                    controller: carbsController,
                                    label: 'Carbs (g)',
                                    hint: '45',
                                    keyboardType: TextInputType.number,
                                    validator: (value) {
                                      if (value?.isEmpty ?? true) {
                                        return 'Required';
                                      }
                                      if (double.tryParse(value!) == null) {
                                        return 'Invalid number';
                                      }
                                      return null;
                                    },
                                  ),
                                ),
                                const Gap(12),
                                Expanded(
                                  child: _buildTextField(
                                    controller: proteinsController,
                                    label: 'Protein (g)',
                                    hint: '8',
                                    keyboardType: TextInputType.number,
                                    validator: (value) {
                                      if (value?.isEmpty ?? true) {
                                        return 'Required';
                                      }
                                      if (double.tryParse(value!) == null) {
                                        return 'Invalid number';
                                      }
                                      return null;
                                    },
                                  ),
                                ),
                              ],
                            ),
                            const Gap(16),
                            Row(
                              children: [
                                Expanded(
                                  child: _buildTextField(
                                    controller: fatsController,
                                    label: 'Fats (g)',
                                    hint: '2',
                                    keyboardType: TextInputType.number,
                                    validator: (value) {
                                      if (value?.isEmpty ?? true) {
                                        return 'Required';
                                      }
                                      if (double.tryParse(value!) == null) {
                                        return 'Invalid number';
                                      }
                                      return null;
                                    },
                                  ),
                                ),
                                const Gap(12),
                                Expanded(
                                  child: _buildTextField(
                                    controller: fiberController,
                                    label: 'Fiber (g)',
                                    hint: '1.5',
                                    keyboardType: TextInputType.number,
                                    validator: (value) {
                                      if (value?.isEmpty ?? true) {
                                        return 'Required';
                                      }
                                      if (double.tryParse(value!) == null) {
                                        return 'Invalid number';
                                      }
                                      return null;
                                    },
                                  ),
                                ),
                              ],
                            ),
                            const Gap(16),
                            // Show calculated total
                            Container(
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                color: ThemeUtils.$primaryColor.withOpacity(
                                  0.1,
                                ),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(
                                  color: ThemeUtils.$primaryColor.withOpacity(
                                    0.3,
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                children: [
                                  const Text(
                                    'Total Calories (calculated):',
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 16,
                                    ),
                                  ),
                                  Text(
                                    '${((double.tryParse(carbsController.text) ?? 0) * 4 + (double.tryParse(proteinsController.text) ?? 0) * 4 + (double.tryParse(fatsController.text) ?? 0) * 9 + (double.tryParse(fiberController.text) ?? 0) * 2).round()} kcal',
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 18,
                                      color: ThemeUtils.$primaryColor,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ],
                      const Gap(100), // Space for button
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
      bottomNavigationBar: Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: ThemeUtils.$secondaryColor,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.05),
              blurRadius: 10,
              offset: const Offset(0, -5),
            ),
          ],
        ),
        child: SafeArea(
          child: Row(
            children: [
              if (currentStep.value > 0)
                Expanded(
                  child: OutlinedButton(
                    onPressed: () {
                      currentStep.value = 0;
                    },
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      side: BorderSide(
                        color: ThemeUtils.$primaryColor,
                        width: 2,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: const Text(
                      'Back',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),
              if (currentStep.value > 0) const Gap(12),
              Expanded(
                flex: currentStep.value == 0 ? 1 : 2,
                child: ElevatedButton(
                  onPressed: isSubmitting.value
                      ? null
                      : () {
                          if (currentStep.value == 0) {
                            if (formKey.currentState?.validate() ?? false) {
                              if (selectedMacroNutrient.value == null) {
                                ScaffoldMessenger.of(context).showSnackBar(
                                  const SnackBar(
                                    content: Text(
                                      'Please select macro nutrient',
                                    ),
                                    backgroundColor: Colors.orange,
                                  ),
                                );
                                return;
                              }
                              if (selectedMealType.value == null) {
                                ScaffoldMessenger.of(context).showSnackBar(
                                  const SnackBar(
                                    content: Text('Please select meal type'),
                                    backgroundColor: Colors.orange,
                                  ),
                                );
                                return;
                              }
                              currentStep.value = 1;
                            }
                          } else {
                            handleSubmit();
                          }
                        },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: ThemeUtils.$primaryColor,
                    foregroundColor: ThemeUtils.$secondaryColor,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 3,
                  ),
                  child: isSubmitting.value
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor: AlwaysStoppedAnimation(
                              ThemeUtils.$secondaryColor,
                            ),
                          ),
                        )
                      : Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text(
                              currentStep.value == 0 ? 'Next' : 'Submit',
                              style: const TextStyle(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            const Gap(8),
                            Icon(
                              currentStep.value == 0
                                  ? FluentIcons.arrow_right_24_filled
                                  : FluentIcons.checkmark_24_filled,
                              size: 20,
                            ),
                          ],
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildStepIndicator({
    required int step,
    required String title,
    required bool isActive,
    required bool isCompleted,
  }) {
    return Column(
      children: [
        Container(
          width: 40,
          height: 40,
          decoration: BoxDecoration(
            color: isCompleted || isActive
                ? ThemeUtils.$primaryColor
                : Colors.grey[300],
            shape: BoxShape.circle,
            boxShadow: isActive
                ? [
                    BoxShadow(
                      color: ThemeUtils.$primaryColor.withOpacity(0.4),
                      blurRadius: 8,
                      spreadRadius: 2,
                    ),
                  ]
                : null,
          ),
          child: Center(
            child: isCompleted
                ? const Icon(
                    FluentIcons.checkmark_24_filled,
                    color: ThemeUtils.$secondaryColor,
                    size: 20,
                  )
                : Text(
                    '$step',
                    style: TextStyle(
                      color: isActive
                          ? ThemeUtils.$secondaryColor
                          : Colors.grey[600],
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                    ),
                  ),
          ),
        ),
        const Gap(8),
        Text(
          title,
          style: TextStyle(
            fontSize: 12,
            fontWeight: isActive ? FontWeight.bold : FontWeight.normal,
            color: isActive ? ThemeUtils.$primaryColor : Colors.grey[600],
          ),
        ),
      ],
    );
  }

  Widget _buildSectionCard({
    required IconData icon,
    required String title,
    required List<Widget> children,
  }) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: ThemeUtils.$secondaryColor,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: ThemeUtils.$primaryColor.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(icon, color: ThemeUtils.$primaryColor, size: 24),
              ),
              const Gap(12),
              Text(
                title,
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: ThemeUtils.$primaryColor,
                ),
              ),
            ],
          ),
          const Gap(20),
          ...children,
        ],
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    IconData? icon,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Colors.grey[700],
          ),
        ),
        const Gap(8),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          validator: validator,
          decoration: InputDecoration(
            hintText: hint,
            prefixIcon: icon != null
                ? Icon(icon, color: ThemeUtils.$primaryColor.withOpacity(0.6))
                : null,
            filled: true,
            fillColor: ThemeUtils.$backgroundColor,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide.none,
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(
                color: Colors.grey.withOpacity(0.2),
                width: 1,
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: ThemeUtils.$primaryColor, width: 2),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: ThemeUtils.$error, width: 1),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 14,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildStringDropdown({
    required String label,
    required String hint,
    required IconData icon,
    required String? value,
    required List<String> items,
    required void Function(String?) onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Colors.grey[700],
          ),
        ),
        const Gap(8),
        DropdownButtonFormField<String>(
          value: value,
          hint: Text(hint),
          decoration: InputDecoration(
            prefixIcon: Icon(
              icon,
              color: ThemeUtils.$primaryColor.withOpacity(0.6),
            ),
            filled: true,
            fillColor: ThemeUtils.$backgroundColor,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide.none,
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(
                color: Colors.grey.withOpacity(0.2),
                width: 1,
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: ThemeUtils.$primaryColor, width: 2),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 14,
            ),
          ),
          items: items.map((item) {
            return DropdownMenuItem(value: item, child: Text(item));
          }).toList(),
          onChanged: onChanged,
        ),
      ],
    );
  }

  Widget _buildMealTypeDropdown({
    required String label,
    required String hint,
    required IconData icon,
    required MealTypeEnum? value,
    required List<MealTypeEnum> items,
    required void Function(MealTypeEnum?) onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Colors.grey[700],
          ),
        ),
        const Gap(8),
        DropdownButtonFormField<MealTypeEnum>(
          value: value,
          hint: Text(hint),
          decoration: InputDecoration(
            prefixIcon: Icon(
              icon,
              color: ThemeUtils.$primaryColor.withOpacity(0.6),
            ),
            filled: true,
            fillColor: ThemeUtils.$backgroundColor,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide.none,
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(
                color: Colors.grey.withOpacity(0.2),
                width: 1,
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide(color: ThemeUtils.$primaryColor, width: 2),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 14,
            ),
          ),
          items: items.map((item) {
            return DropdownMenuItem(
              value: item,
              child: Text(item.toString().split('.').last),
            );
          }).toList(),
          onChanged: onChanged,
        ),
      ],
    );
  }
}
